version: '3'
services:
  everything-tech:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    environment:
      - WDS_SOCKET_PORT=0
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules